server {
  listen 80;
  server_name admin.local;

  location / {
    proxy_pass http://admin-ui:5173;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}

server {
  listen 80;
  server_name ordering-dev.local;

  location / {
    proxy_pass http://ordering-portal-develop:5174;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}

server {
  listen 80;
  server_name ordering-master.local;

  location / {
    proxy_pass http://ordering-portal-master:5175;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}